version: '3'

services:
  nginx:
    image: nginx:stable-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - db
      - kafka
    networks:
      - tasty-net
  db:
    container_name: db
    hostname: db
    image: mongo:8.0.0-rc13-jammy
    ports:
      - "27017:27017"
    volumes:
      - 'db_data:/data/db'
    networks:
      - tasty-net
  zookeeper:
    container_name: zookeeper_tasty
    hostname: zookeeper
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"
    networks:
      - tasty-net
  kafka:
    container_name: kafka_tasty
    hostname: kafka
    image: bitnami/kafka:3.4.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - tasty-net
volumes:
  db_data:
    driver: local

networks:
  tasty-net:
    external: true